version: '3.8'
services:
  web:
    build: ./web-frontend
    ports:
      - "80:80"
  api:
    build: ./fastapi-service
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi-service:/app
  mongo:
    image: mongo:4.4
    container_name: my_mongodb_container
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  mongo_data:

labels:
  kompose.service.type: LoadBalancer