version: '3.8'
services:
  web:
    build: ./web-frontend
    ports:
      - "80:80"
  api:
    build: ./fastapi-service
    ports:
      - "8000:8000"
  mongo:
    image: mongo:4.4
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  mongo_data: