apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;
        server_name http://localhost:8000;

        location / {
          proxy_pass http://localhost:8000;  # Gunicorn is running on port 8000
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # ... other configuration ...
      }
    }
